#! /bin/sh

# Natual Scrolling
xinput set-int-prop "SynPS/2 Synaptics TouchPad" "libinput Natural Scrolling Enabled" 8 1

# Enable two and three finger clicking
bash -c 'xinput set-prop "SynPS/2 Synaptics TouchPad" "libinput Click Method Enabled" {0,1}'

# Kill all programs
pkill sxhkd
pkill compton
pkill dunst
pkill lemonbar.sh
killall check-battery.sh
pkill xautolock

# Run background programs
sxhkd &
compton &
nitrogen --restore &
~/.config/lemonbar/lemonbar.sh &
~/.config/bspwm/check-battery.sh

# Configure desktops
bspc monitor -d ""
bspc monitor -a ""
bspc monitor -a ""
bspc monitor -a ""

# bspwm config
bspc config border_width         1
bspc config window_gap          12
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config single_monocle       true

# Nord theme
bspc config normal_border_color   "#81a1c1"
bspc config active_border_color   "#8fbcbb"
bspc config focused_border_color  "#8fbcbb"
bspc config presel_feedback_color "#d08770"

# Sets master/stack layout in bspwm
bsp-layout set tall -- --master-size 0.51

# bspwm rules
bspc rule -a Thorium-Browser desktop=^1 follow=on
bspc rule -a Kitty desktop=^2 follow=on

